kind: pipeline
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: build
  image: golang:1.12.4-alpine
  commands:
  - apk add --no-cache --update build-base bash git
  - mkdir -p bin
  - wget https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -O bin/dep
  - chmod u+x bin/dep
  - export PATH=$PWD/bin:$PATH
  - go mod init
  - make

- name: publish-amd64-image
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    custom_dns: 1.1.1.1
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/csi-node-driver-registrar
    tag: "${DRONE_BRANCH}-amd64"
    username:
      from_secret: docker_username
  when:
    branch:
    - lh-10132020
    event:
    - push

- name: publish-tagged-amd64-image
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    custom_dns: 1.1.1.1
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/csi-node-driver-registrar
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    branch:
    - lh-10132020
    event:
    - tag
---
kind: pipeline
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: fetch
  image: arm64v8/alpine
  commands:
  - apk add git
  - git fetch --tags

- name: build
  image: golang:1.12.4-alpine
  commands:
  - apk add --no-cache --update build-base bash git
  - mkdir -p bin
  - wget https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-arm64 -O bin/dep
  - chmod u+x bin/dep
  - export PATH=$PWD/bin:$PATH
  - go mod init
  - GOARCH=arm64 make

- name: publish-arm64-image
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    custom_dns: 1.1.1.1
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/csi-node-driver-registrar
    tag: "${DRONE_BRANCH}-arm64"
    username:
      from_secret: docker_username
  when:
    branch:
    - lh-10132020
    event:
    - push

- name: publish-tagged-arm64-image
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    custom_dns: 1.1.1.1
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/csi-node-driver-registrar
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    branch:
    - lh-10132020
    event:
    - tag
---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: create image manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "longhornio/csi-node-driver-registrar:${DRONE_BRANCH}"
    template: "longhornio/csi-node-driver-registrar:${DRONE_BRANCH}-ARCH"
  when:
    instance:
    - drone-publish.longhorn.io
    branch:
    - lh-10132020
    event:
    - push

- name: create tagged image manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "longhornio/csi-node-driver-registrar:${DRONE_TAG}"
    template: "longhornio/csi-node-driver-registrar:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.longhorn.io
    branch:
    - lh-10132020
    event:
    - tag

depends_on:
- default-amd64
- default-arm64
